### ISSUE TITLE
Issue with using action

### ISSUE THREAD

**Issue by sjmiller609** [cloudposse/github-action-setup-atmos#20]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

I used the configuration in the README but have this error:

```
Error: Unable to resolve action cloudposse/setup-atmos, repository not found
```

## Steps to Reproduce
```
name: Run a Terraform plan
on:
  pull_request:
    branches:
      - main

jobs:
  demo:
    runs-on:
      - self-hosted
    steps:
      - uses: hashicorp/setup-terraform@v2
      - name: Setup Atmos
        uses: cloudposse/setup-atmos@v1
        with:
          install-wrapper: false
      - name: Atmos describe affected
        run: |
          set -xe
          atmos describe affected
      - run: echo ${{ steps.atmos.outputs.stdout }}
      - run: echo ${{ steps.atmos.outputs.stderr }}
      - run: echo ${{ steps.atmos.outputs.exitcode }}
```

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

## Additional Context

However, this works:

```
      - name: Setup Atmos
        uses: cloudposse/github-action-setup-atmos@922691acdf3001151f15010385c5b1dd5427f57b
        with:
          install-wrapper: false
```
