### ISSUE TITLE
Read from version file `atmos-version-file`

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/github-action-setup-atmos#97]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Similar to https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-file-input

I have the atmos version supplied in multiple places. It would be nice to have it in a single place such as with a `.python-version` file or `.atmos-version` file or perhaps support the asdf file `.tool-versions`

e.g.

```yaml
  - name: Setup atmos
    uses: cloudposse/github-action-setup-atmos@v2
    with:
      install-wrapper: true
      atmos-version-file: .atmos-version
```

## Expected Behavior

Centralized place for atmos version

## Use Case

See above

## Describe Ideal Solution

See above

## Alternatives Considered

Create a repo `.atmos-version`
Use a github action to read its contents and save the version to an output
Then read the output in this action

## Additional Context

N/A
